#!/usr/bin/env bash
# Lets a *release* build reach the local P7 payload server over plain HTTP (docs/PROMPTS.md P7).
#
# Why this exists: expo prebuild puts `android:usesCleartextTraffic="true"` only in
# android/app/src/debug/AndroidManifest.xml. Release builds therefore block cleartext, and the
# P7 baseline's fetch to http://127.0.0.1:8787 fails silently — the app renders a blank page and
# every marker after appStart goes missing. That is exactly how it first failed here.
#
# `android/` is gitignored and regenerated by `expo prebuild`, so this is a script rather than a
# committed edit: re-run it after any prebuild, before scripts/p7-build.sh.
#
# Scope is deliberately narrow — loopback only, which is all `adb reverse` needs. This does not
# enable cleartext to the internet at large, and it is benchmark scaffolding, not app config.
set -euo pipefail

MANIFEST="android/app/src/main/AndroidManifest.xml"
CONFIG_DIR="android/app/src/main/res/xml"
CONFIG="$CONFIG_DIR/network_security_config.xml"

if [ ! -f "$MANIFEST" ]; then
  echo "no $MANIFEST — run 'npx expo prebuild -p android' first" >&2
  exit 1
fi

mkdir -p "$CONFIG_DIR"
cat > "$CONFIG" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/p7-enable-cleartext.sh. Loopback only: the P7 payload server is
     reached through `adb reverse tcp:8787`, so from the app it is 127.0.0.1. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
XML

if grep -q 'android:networkSecurityConfig' "$MANIFEST"; then
  echo "manifest already references a networkSecurityConfig — leaving it alone"
else
  # Insert the attribute on the <application> tag only.
  perl -pi -e 's/(<application )/$1android:networkSecurityConfig="\@xml\/network_security_config" /' "$MANIFEST"
  echo "patched $MANIFEST"
fi

echo "wrote $CONFIG"
grep -o 'android:networkSecurityConfig="[^"]*"' "$MANIFEST"
